# Generated by Django 4.2.5 on 2023-09-10 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_parameter_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinfo',
            old_name='price_rrc',
            new_name='recommended_price',
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_infos', to='main.product', verbose_name='Товар'),
        ),
    ]
