# Generated by Django 4.2.5 on 2023-09-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_productinfo_unique_product_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара'),
        ),
    ]
