# Generated by Django 4.2.5 on 2023-09-16 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_shop_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='file',
        ),
    ]
