# Generated by Django 4.2.5 on 2023-09-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_confirmemailtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл с товарами'),
        ),
    ]
