# Generated by Django 4.2.5 on 2023-09-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_shop_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinfo',
            old_name='recommended_price',
            new_name='price_rrc',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='external_id',
            field=models.PositiveIntegerField(default=111, verbose_name='Внешний ID'),
            preserve_default=False,
        ),
    ]
